### ISSUE TITLE
Feed title? 

### ISSUE THREAD

**Issue by Nick-Shannon** [snarfed/twitter-atom#12]
Twitter Atoms feeds is fantastic. 

Quick question/comment. 

The title for each feed item is the same as the feed content. 
It would be better to have the **name**  as the title. 
Or, an option to prefix the content with the **name.** 

For example: 
 PhoneDog: Minecraft Earth launches in the U.S. in early access phonedog.com/2019/11/12/min… by @alw

This way I can see who the tweet was from. 

Original XML:

```
<entry>
<title>Minecraft Earth launches in the U.S. in early access phonedog.com/2019/11/12/min… by @alw</title>
<link rel="alternate" type="text/html" href="https://twitter.com/PhoneDog/status/1194386695648468992" /> 
<author> 
<name>PhoneDog</name>
<uri>https://twitter.com/PhoneDog</uri> 
</author> 
<issued>2019-11-12T14:49:13-08:00</issued> 
<modified>2019-11-12T14:49:13-08:00</modified> 
<id>https://twitter.com/PhoneDog/status/1194386695648468992</id> 
<content type="application/xhtml+xml"> 
<div xmlns="http://www.w3.org/1999/xhtml"> 
Minecraft Earth launches in the U.S. in early access 
<a href="https://www.phonedog.com/2019/11/12/minecraft-earth-us-android-iphone-download">phonedog.com/2019/11/12/min…</a> 
by 
<a href="https://twitter.com/alw">@alw</a> 
<p> 
<a class="link" href="https://twitter.com/PhoneDog/status/1194386695648468992"> 
<img class="u-photo" src="https://pbs.twimg.com/media/EJNQXgNU0AY8seB.jpg" alt="" /> 
</a> 
</p> 
</div> 
</content> 
<activity:object-type xmlns:activity="http://activitystrea.ms/spec/1.0/">http://activitystrea.ms/schema/1.0/note</activity:object-type> 
<activity:verb xmlns:activity="http://activitystrea.ms/spec/1.0/">http://activitystrea.ms/schema/1.0/post</activity:verb>
</entry>
```

**Comment by snarfed** [comment]
hey, thanks for the feedback. interesting idea!

out of curiosity, which reader are you using? does it not show the author visibly? twitter-atom already populates the `<author>` element with the author's name and URL, as seen in the RSS XML you posted, which readers can and should display. here's an example from mine, [NewsBlur](https://www.newsblur.com/):

![image](https://user-images.githubusercontent.com/778068/68794713-67d6fd00-0604-11ea-9d6a-284e174bcbec.png)

readers control their UIs, so they're really the right place to make decisions about how and where to render each piece of content. this would be a small change, but twitter-atom is the wrong place to try to affect UI, so i'm a bit reluctant to undermine readers like this, especially since people use twitter-atom in dozens of different readers.

**Comment by Nick-Shannon** [comment]
Yeah, I understand why you won't want to change twitter-atom as that may upset things for other users. 

I was experimenting with using twitter-atom in an iOS widget: 

<img src="https://newzea1ander.files.wordpress.com/2019/11/image.jpeg" alt="image" style="max-width:100%;">


It looks nice, but has no author info. Which actually isn't a big deal - can live without that. 
But thanks for your consideration.
