### ISSUE TITLE
Apology and Request

### ISSUE THREAD

**Issue by UA-Archiver** [snarfed/twitter-atom#14]
Hi, so about 2 weeks ago, a small malfunction in an application we use caused it (to crash and boot loop) to constantly send requests to the app and cause a mini DoS.
(The application was configured to auto refresh all feeds on boot and then start the refresh cycles)

https://github.com/snarfed/twitter-atom/blob/a7dd9debb65446cb50a50592590f71db58f14857/main.py#L38-L40

I would like to apologies for this error and we have in the last 2 weeks implemented some patches to prevent this from happening again.

We were hoping to get unblacklisted from the service as we are unable to get our own instance running due to billing issues or get an alternative app running with our resources.

The default refresh rate was set to about every 4 to 5 mins but we are also ready to increase this to 8 to 10 mins pre refresh incase our refresh rate is still to aggressive and you agree to allow us to still use your service, 
Which include
- Adding a proper function to stop boot loops (auto stop if we face 2 crashes in under 10 mins)
- Set bot to NOT load feed at start but to wait just start waiting according to refresh rate

Incase you wish to leave us blacklisted, we understand.
Thanks in advance

**Comment by snarfed** [comment]
Thanks for the note and detailed explanation! Glad to hear about the improvements. Just so you know, twitter-atom caches results for 15m, so you won't get any benefit from polling more frequently than that.

https://github.com/snarfed/twitter-atom/blob/a7dd9debb65446cb50a50592590f71db58f14857/main.py#L15=

Could you merge your lists so that you're requesting only one or a few lists every 15m? I'm happy to remove the blacklist, but twitter-atom is primarily aimed at individual users, not developers, and it isn't exactly industrial grade or highly scalable.

**Comment by UA-Archiver** [comment]
The application is only in use by me and a few friends (about a group of 5 total people), so its not in a development environment.

For the number of lists, I have asked the person who added them and am working on cutting them down, I aim to get the number of lists around half of what it was (so at 5)

And thanks for the note on the cache duration of 15 minutes, I believe putting these on a slower schedule will be nicer for the raspberry pi.

**Comment by snarfed** [comment]
Sounds good! I've un-blocklisted you. Thanks again for the explanation and for working with me!
